name: Deploy

on: deployment
 
jobs:
  deploy-DEV:
    name: Deploy to DEV environment
    if: ${{ github.event.deployment.environment }} == DEV
    concurrency: DEV
    permissions:
      deployments: write
    runs-on: ubuntu-latest

    steps:
      - name: Update deployment status (pending)
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'pending'
          deployment-id: ${{ github.event.deployment.id }}

      - name: Deploy my app
        run: |
          # add your deployment code here
          echo Deploying...
          sleep 1s
          echo Done!
          
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          deployment-id: ${{ github.event.deployment.id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          deployment-id: ${{ github.event.deployment.id }}
